BUG: Fix required Python version in package setup
Fix required Python version in package setup.

Fixes:
```
ERROR: Package 'braintransform' requires a different Python: 3.8.12 not in '==3.6'
```

raised in:
https://github.com/brainhackorg/braintransform/runs/5175901365?check_suite_focus=true#step:7:58